name: scrape

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:       # manual trigger option

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ⬇️ Download artifact
      - name: Download saved posts
        uses: actions/download-artifact@v3
        with:
          name: saved-posts
          path: .

      - name: Run scraper
        run: python scraper.py

      # ⬆️ Upload updated data.json
      - name: Upload saved posts
        uses: actions/upload-artifact@v3
        with:
          name: saved-posts
          path: data.json
